### ISSUE TITLE
 Unexpected server response: 503

### ISSUE THREAD

**Issue by GitGepeng** [SchneeHertz/node-edge-tts#1]
Unexpected server response: 503
![image](https://github.com/SchneeHertz/node-edge-tts/assets/17194342/cfd8b1f5-3c6c-4585-982e-724cee67eadf)

**Comment by SchneeHertz** [comment]
If you are in mainland China, it is due to network reasons and you need to configure a proxy.
like: `npx node-edge-tts -t "Hello World" -p "http://127.0.0.1:7890"`

**Comment by GitGepeng** [comment]
thanks a lot!
I found that at the same time you answered me!
I will use the proxy.thank you a lot again!

**Comment by GitGepeng** [comment]
Thank you a lot!
I found that at the same time you answered me!
I will use the proxy.Thank you a lot again!

**Comment by arleyGuoLei** [comment]
how to catch the ws 503 error to retry?

<img width="568" alt="Image" src="https://github.com/user-attachments/assets/a3767f06-10eb-4864-a521-6a12cfa1fe85" />

```ts
 const maxRetries = 3
  const retryDelay = 1000

  const ttsWithRetry = async (
    ttsInstance: EdgeTTS,
    text: string,
    audioPath: string,
    attempt = 1
  ): Promise<void> => {
    try {
      await ttsInstance.ttsPromise(text, audioPath)
    } catch (err) { // 
      // not catch the 503
      console.error('log =>  ~ ttsWithRetry ~ err:', err)

      if (attempt < maxRetries) {
        ttsLog(`Retrying TTS for text: ${text}, attempt: ${attempt}`)

        await new Promise((resolve) => setTimeout(resolve, retryDelay))
        return ttsWithRetry(ttsInstance, text, audioPath, attempt + 1)
      } else {
        throw err
      }
    }
  }

```
