### ISSUE TITLE
add rate, volume and pitch control attr

### ISSUE THREAD

**Issue by aoaoms** [SchneeHertz/node-edge-tts#2]
please add more attr, like this:

`"<speak version='1.0' xmlns='http://www.w3.org/2001/10/synthesis' xml:lang='en-US'>"
        f"<voice name='{voice}'><prosody pitch='{pitch}' rate='{rate}' volume='{volume}'>"
        f"{text}</prosody></voice></speak>"`

it's useful, thanks

**Comment by SchneeHertz** [comment]
v1.2.3 has added corresponding options
